#!/usr/bin/env bash
# script to configure Nginx for redirection

apt update
apt install nginx -y

echo "Hello World!" > /var/www/html/index.html

# create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create a temporary file with the redirection rule
# configure nginx to use custom 404 page
echo -e "\tserver_name _;
\tlocation /redirect_me {
\t\treturn 301 https://www.linkedin.com/in/keamogetse-mohlala/;
\t}

\terror_page 404 /404.html;
\tlocation = /404.html {
\t\troot /var/www/html;
\t\tinternal;
\t}
" | tee /tmp/new_config

# Insert the redirection rule into the existing Nginx configuration
sed -i '/server_name _;/{
    r /tmp/new_config
    d
}' /etc/nginx/sites-available/default

rm /tmp/new_config

# Test the Nginx configuration for syntax errors
# If the test is successful, reload Nginx to apply the changes
if ! nginx -t
then
    service nginx start
else
    echo "Nginx configuration test failed"
    exit 1
fi
