#!/usr/bin/env bash
# This script installs and configures HAproxy on the 'lb-01' server

# Update package lists
apt-get update

# Install HAProxy
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | tee /etc/haproxy/haproxy.cfg
frontend retiredscientist_front
    bind *:80
    mode http
    default_backend retiredscientist_back

backend retiredscientist_back
    balance roundrobin
    server 530824-web-01 web-01.retiredscientist.tech:80 check
    server 530824-web-02 web-02.retiredscientist.tech:80 check
EOF

# Verify configuration and restart HAProxy
haproxy -c -f /etc/haproxy/haproxy.cfg
service haproxy restart
