#!/usr/bin/env bash
# This script is designed to configure Nginx on an Ubuntu conatiner
# to listen to port 80 by removing the default site configuration
# and creating a link to the default configuration file

# Check if the user has sudo privileges
if [ ! "$(id -u)" -eq 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
