#!/usr/bin/env bash
#Create the PID file containing the PID of this script
#Main loop that runs indefinitely
#Handles sigter, sigint and sigquit
echo $$ > /var/run/myscript.pid

handle_sigterm()
{
echo "I hate the kill command"
rm /var/run/myscript.pid
exit  0
}

handle_sigint()
{
echo "Y U no love me?!"
exit  0
}

handle_sigquit()
{
rm /var/run/myscript.pid
exit  0
}


trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while true; do
echo "To infinity and beyond"
sleep  1
done
