#!/usr/bin/env bash
#this scripts runs an indefinite loop and prints a message
#when it receives a termination signal
handle_sigterm()
{
echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while true;
do
echo "To infinity and beyond"
sleep 2
done
