#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes
h=0
while [ $h -le 12 ];
do
echo "Hour: $((h))"
mm=1
while [ $mm -le 59 ];
do
echo "$((mm))"
mm=$((mm + 1))
done
h=$((h + 1))
done
